# Generated by Django 3.1.6 on 2021-02-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210223_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=50)),
                ('Job_desp', models.TextField(max_length=500)),
                ('Job_type', models.CharField(max_length=50)),
                ('Job_category', models.CharField(max_length=50)),
                ('Job_respon', models.TextField(max_length=500)),
                ('Job_edu_exp', models.TextField(max_length=500)),
                ('Job_benefit', models.TextField(max_length=500)),
                ('Vacancy', models.IntegerField(default='5')),
                ('Education', models.CharField(max_length=50)),
                ('Experience', models.CharField(max_length=50)),
                ('Job_loc', models.CharField(max_length=50)),
                ('start_salary', models.CharField(default='5k', max_length=50)),
                ('end_salary', models.CharField(default='8k', max_length=50)),
                ('Gender', models.CharField(default='Any', max_length=50)),
                ('App_deadline', models.DateField(default='2020-12-01')),
                ('Published', models.DateField(auto_now_add=True)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
