# Generated by Django 3.1.6 on 2021-02-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='comp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.company'),
        ),
    ]
