# Generated by Django 3.1.6 on 2021-02-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210223_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='comp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
