# Generated by Django 3.1.6 on 2021-02-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210223_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_table',
            old_name='is_verifed',
            new_name='is_verified',
        ),
    ]
