# Generated by Django 3.1.6 on 2021-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210226_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='ver_doc',
            field=models.FileField(default='/ver_doc/default.pdf', upload_to='ver_doc/'),
        ),
    ]
